### PR TITLE
Marvel Guides: correct Volume of X-Force books in Part 15.4

### PR DESCRIPTION
**Pull request by OddBloke**
There is no 2020 volume, these are part of the ongoing 2019 volume.

### CODE REVIEW

**Review by DieselTech — APPROVED** [review]
Confirmed

**Comment by DieselTech** [comment]
Ah thank you. I had noticed this after they were merged in last time but I haven't gotten around to changing it.

**Comment by flips22** [comment]
What series is this on comicvine?  Based on what I have as the comicvine ID, the year is 2020. https://comicvine.gamespot.com/x-force/4050-122668/

**Comment by DieselTech** [comment]
I think the problem here comes from how CV has it listed. Issues 1-4 were put our during 2019.

image

**Comment by flips22** [comment]
Sure, but the the entire series is tagged at a volume year starting with 2020. So the cv tagger tags everything as volume year 2020.  If you change it, then komga won't find it.
image

**Comment by DieselTech** [comment]
> Sure, but the the entire series is tagged at a volume year starting with 2020. So the cv tagger tags everything as volume year 2020. If you change it, then komga won't find it.

I had the exact opposite problem, mylar had already tagged the series as as 2019 in my library and the .cbl wouldn't load in because komga couldn't find it. I tried looking at the CV edit history for the volume but it's not showing me changes. I bet it has to do with when the series was added they used 2019 to start with and updated after the first few issues were out.

**Comment by flips22** [comment]
What does your series look like in mylar? I bet you have the Spanish language series.
image

**Comment by DieselTech** [comment]
image

**Comment by flips22** [comment]
It looks like, it is just in the wrong folder.  :)  I bet when you added it, it was listed at x-Force (2019) on CV, and then they changed it a while later.  So if you add it now, it will be in the 2020 folder like mine.  For me the cbl import in komga fails.
Screenshot 2023-08-21 8 07 14 PM

**Comment by flips22** [comment]
yep, wayback machine to the rescue: 
image

**Comment by DieselTech** [comment]
So well into 2020 they had it listed as 2019. Which to me makes sense, it came out in 2019. 

If CV updates after mylar already makes the series folders it won't change where it's stored at. I wonder how many people have the different versions of it. Do you know when you added the series to your own library? 

Also I'm not really inclined to go off cover date for things. In store date is the metric IMO because that is when people would have their hands on it. 

I wonder if we would get shot down from changing the series on CV to correct it.

**Comment by flips22** [comment]
I looked at mine, yeah the files are also in a 2019 folder for me as well.    Which yeah I wasn't thinking.  Komga goes off of the meta data, so as long as your metadata is right, then it should work.  Maybe a refresh in mylar?
image

**Comment by OddBloke** [comment]
I made this change to at least align all of the issues with the same volume. I wouldn't particularly mind it changing to 2020.

However, I'm not convinced that CV actually has it right here. The description on https://www.marvel.com/comics/collection/102548/x-force_by_benjamin_percy_vol_6_trade_paperback, which was published in June of this year, refers to the series as X-Force (2019).
image

**Comment by OddBloke** [comment]
(Thanks for the speedy merge BTW!)

**Comment by DieselTech** [comment]
> However, I'm not convinced that CV actually has it right here

That's my hesitation too. If they are wrong then that's on them. I don't want to publish known bad info just to make their lives easier.

**Pull request merged**
