### PR TITLE
removed duplicates from marvel CBRO with events Part 4

### PR DESCRIPTION
**Pull request by rad96**
Was going through adding this CBLs into my komga instance, it highlighted this issues as duplicates in CBL and I did my best removing it
I struggle to find original reading order in CBRO site so I "guessed" and make decision based on issues placement in list order

### CODE REVIEW

**Comment by morsok** [comment]
>  I struggle to find original reading order in CBRO site so I "guessed" and make decision based on issues placement in list order

It's here: https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-4/

**Comment by rad96** [comment]
> > I struggle to find original reading order in CBRO site so I "guessed" and make decision based on issues placement in list order
> 
> It's here: https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-4/

Can't find Damage Control in link you provided

**Comment by falo2k** [comment]
It is probably in one of the events - CBRO embeds links to events within the lists, which often are what cause duplication if those lists are expanded out in the cbl.

**Comment by morsok** [comment]
Yeah it's in this event: https://comicbookreadingorders.com/marvel/events/inferno-reading-order/

**Comment by falo2k** [comment]
Looks like there were two Damage Control 1989 series.  Issue 4 of the first is in Inferno, then issues 1-4 of the second in Acts of Vengeance.  So both issue 4s should exist, but the second set (1-4) need updating to reflect the comicvine volume and issue IDs of the Volume 2 series.

**Comment by falo2k** [comment]
Yep, that's the right ID 👍

**Comment by rad96** [comment]
Fixed id's for vol 2 of damage control

**Review by DieselTech — APPROVED** [review]

**Pull request merged**
