### PR TITLE
Removed duplicates from Marvel CBRO with Events part 5

### PR DESCRIPTION
**Pull request by rad96**
Removed issues which intersects inside various events.

### CODE REVIEW

**Comment by DieselTech** [comment]
Can you explain the reasoning behind the removals? The list is in question is a "with events" type of list to begin with, so why would event based issues be removed?

**Comment by rad96** [comment]
> Can you explain the reasoning behind the removals? The list is in question is a "with events" type of list to begin with, so why would event based issues be removed?

Komga does not allow CBL match till duplicates are resolved

**Comment by DieselTech** [comment]
Ah okay I see, it is about removing duplicates like the title says. I got confused for a second by the first post that just says: `Removed issues which intersects inside various events.`

**Comment by rad96** [comment]
I don't see any statement about shall they be present in list or not
If they should then you can close all duplicate related PRs and I will just go along with my fork when they will be removed

**Comment by rad96** [comment]
This is old one, I didn't know much about comics back then

**Comment by rad96** [comment]
X-men is this
https://comicbookreadingorders.com/marvel/events/fatal-attractions-reading-order/
and https://comicbookreadingorders.com/marvel/events/onslaught-saga-reading-order/

X-force is main https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-5/
and https://comicbookreadingorders.com/marvel/events/onslaught-saga-reading-order/

Amazing spider-man https://comicbookreadingorders.com/marvel/events/second-clone-saga-reading-order/
and https://comicbookreadingorders.com/marvel/events/onslaught-saga-reading-order/
same for spider man 72

Green goblin is main https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-5/
and https://comicbookreadingorders.com/marvel/events/second-clone-saga-reading-order/

Spectacular Spider-Girl is by error
need to fix https://comicbookreadingorders.com/marvel/events/mc2-reading-order/
will remove from changeset rn

**Comment by rad96** [comment]
Will make separate PR with spider-girl fix

**Review by DieselTech — APPROVED** [review]

**Pull request merged**
